version: "3.8"

services:
  postgres:
    container_name: prescriptions-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: prescriptions
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: prescriptions
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
